### ISSUE TITLE
Using Kafka With One Port

### ISSUE THREAD

**Issue by finepointcgi** [grepplabs/kafka-proxy#101]
Hello,
I have a request from our customer to pass all data though the 443 port from both zookeeper and kafka
eg
![image](https://user-images.githubusercontent.com/12012300/153282791-2186da6e-9c58-45c6-a513-5480a4fc9985.png)
I wonder if this is possible and honestly im not sure where to start.

Thanks,
Mitch

**Comment by everesio** [comment]
Hi, 
this setup is not possible. 

BTW. kafka proxy does not communicate with zookeeper. 
I don't know it it helps but the kafka clients could communicate kafka-proxy, which could route the traffic through SOCK5  or HTTP Proxy.
Kind regards,
Michal
