### ISSUE TITLE
How does tls-same-client-cert-enable work?

### ISSUE THREAD

**Issue by AmiDavidW** [grepplabs/kafka-proxy#103]
Hello,

Is it possible that we use tls-same-client-cert-enable flag to make this connection below working?

kafak(10.0.0.1) <--ssl--> proxy(127.0.0.1) <--ssl--> client
Both ssl connections use the same certificates.

What does the cmd look like if yes?

Thanks,
David

**Comment by everesio** [comment]
Hi,
certificates propagation is not possible. The implementation would require the proxy to know client private key for the signature in the certificateVerifyMsg.

`tls-same-client-cert-enable` is a contributed feature. It provides additional cert check when proxy terminates the TLS traffic.
