### ISSUE TITLE
please upgrade to 3.2.0

### ISSUE THREAD

**Issue by msillence** [grepplabs/kafka-proxy#107]
there's a security issue in 3.1.0 https://mvnrepository.com/artifact/org.apache.kafka/kafka_2.13/3.1.0

**Comment by everesio** [comment]
The security issue is related to the jackson-databind i.e. the the specific java lib and not to the kafka-proxy. 
Additionally there is a fixed lib version https://mvnrepository.com/artifact/org.apache.kafka/kafka_2.13/3.1.1

Nevertheless I shall upgrade the proxy to the newest kafka version soon.

**Comment by msillence** [comment]
> Nevertheless I shall upgrade the proxy to the newest kafka version soon.

Fantastic, thank you

**Comment by everesio** [comment]
Kafka proxy 0.3.1 is compatible with the latest Kafka version (3.2.1)
