### ISSUE TITLE
Address mappings?

### ISSUE THREAD

**Issue by edo-dk-cl** [grepplabs/kafka-proxy#114]
I'm running a docker container with kafka-proxy as entrypoint, the thing is when I try to connect to it i get this message:

`Address mappings broker=xxx.xxx.xxxx.xxx:xxx, listener=0.0.0.0:42178, advertised=0.0.0.0:42178` and I'm not sure what it means but the connection is not established correctly.

Any ideas on what might be happening?

Thanks

**Comment by everesio** [comment]
Kafka proxy is listening on listener=0.0.0.0:42178 and advertises its own address to the client as advertised=0.0.0.0:42178 
i.e. client should/will connect to the 0.0.0.0:42178
