### ISSUE TITLE
Set secrets through environment variables

### ISSUE THREAD

**Issue by rnphilp** [grepplabs/kafka-proxy#126]
Hi,

I'm deploying kafka-proxy as part of an ECS task to allow connection to kafka using sasl username and password. I don't want to define the password directly into the command in the task definition as this will then be visible in the task definition. Is it possible to set the `--sasl-password` argument as an environment variable instead so it can be pulled from secrets managers or paramteter store instead?

Thanks.

**Comment by everesio** [comment]
In the 0.3.5 you can use SASL_PASSWORD env variable.
