### ISSUE TITLE
docker pull on M1 seems to be breaking since 3.4.0

### ISSUE THREAD

**Issue by kobynet** [grepplabs/kafka-proxy#130]
Until version 0.3.3
`docker pull grepplabs/kafka-proxy:v0.3.3`
worked as expected on mac with M1 processor, image was downloaded.
Since version 0.3.4, when trying to run docker pull
`docker pull grepplabs/kafka-proxy:0.3.4`
error is received

> no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by everesio** [comment]
Hi, 
I am just confused as ARM was never supported. 
However I've just added it and you can try version 0.3.6

**Comment by kobynet** [comment]
Thanks, @everesio, seems to be working now.
