### ISSUE TITLE
Pod startup issue after version 0.3.3-all

### ISSUE THREAD

**Issue by dnltech2020** [grepplabs/kafka-proxy#141]
I have been using the Kafka-proxy project for some time, but since all releases after 0.3.3-all,  I’m getting the following error in the pod logs

The pod does show as Running

Error: “@message”:”listen tcp 0.0.0.0:443: bind: permission denied”

when I revert back to 0.3.3-all then everything works fine

I tried release versions 0.3.4-all, 0.3.5-all and 0.3.6-all.  With the same issue on all images.

I have tried editing the security context for the pod to all 

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  cababilities:
    drop:
      - all
    Add:
      - NET_BIND_SERVICE
      - NET_ADMIN
      - SYS_TIME   
    

Please let me know what changed after version 0.3.3-all?

Thanks

**Comment by dnltech2020** [comment]
If I set the listen IP to 0.0.0.0:8080 then the pod works, but I can’t get to it, is it possible on the image that you can allow the NET_BIND_SERVICE for lower port numbers, below 1024?  Thanks I think that would solve the issue

**Comment by everesio** [comment]
@dnltech2020 thank you for reporting. the fix was merged and new version should be released soon.

**Comment by everesio** [comment]
Fixed in v0.3.7
