### ISSUE TITLE
updating to tag 0.3.7-all from 0.3.3-all getting error auth-local-command

### ISSUE THREAD

**Issue by dnltech2020** [grepplabs/kafka-proxy#147]
In old image I'm using the following command
auth-local-command=/opt/kafka-proxy/bin/auth-user
which works fine in tag 0.3.3-all

when updating to 0.3.7-all this is now causing an error on the pod stating that the location does not exist.

I read on document on this github that the auth-user path could be  =/auth-user or =/build/auth-user,  neither one is working in tag 0.3.7-all

can you post the correct path for the auth-local-command for auth-user.

**Comment by everesio** [comment]
@dnltech2020  Thank you for reporting. The plugins were missing in the previous docker image, but now you should find them in the  `/opt/kafka-proxy/bin` directory.

```
$ docker run -it --rm  --entrypoint=/bin/ls grepplabs/kafka-proxy:0.3.8-all   /opt/kafka-proxy/bin
auth-ldap               auth-user               google-id-info          google-id-provider      kafka-proxy             oidc-provider           unsecured-jwt-info      unsecured-jwt-provider
```
