### ISSUE TITLE
[Question] Can I attach 3 bootstrap server endpoints to a single port?

### ISSUE THREAD

**Issue by magiusdarrigo** [grepplabs/kafka-proxy#151]
I have 3 bootstrap server endpoints. Is it possible to specify `--bootstrap-server-mapping` just once and attach all 3 URIs to a single container port? 

Will it automatically round robin between these broker URIs for me? If so, can I see an example of what the command-argument looks like? Thanks

**Comment by everesio** [comment]
Each Kafka broker must be represented as a unique host:port pair. However, you can map only one broker using the "--bootstrap-server-mapping" parameter, and the proxy will dynamically assign ports for you. You should utilize this mapped broker on the client side, and the driver will handle the discovery process.
