### ISSUE TITLE
[Question] If my Kafka brokers are running version 2.8.1, should I be using kafka-proxy version 0.2.9?

### ISSUE THREAD

**Issue by magiusdarrigo** [grepplabs/kafka-proxy#152]
My Kafka brokers are running version 2.8.1

Does this mean the latest version of this kafka-proxy library I can use is 0.2.9?

The table states 3.8.0, but not sure if it means 3.8.x

**Comment by everesio** [comment]
You can use the latest kafka-proxy version i.e. 0.3.8 to run with kafka 2.8.1, as it supports kafka versions from 0.11.0 to at least 3.4.0. Proxy version 0.2.9 supports Kafka versions from 0.11.0 to 2.8.0.
