### ISSUE TITLE
tls: failed to parse private key AWS MSK

### ISSUE THREAD

**Issue by bdgeise** [grepplabs/kafka-proxy#160]
I have an AWS MSK cluster that has been configured for TLS authentication with SSL.  I have followed https://docs.aws.amazon.com/msk/latest/developerguide/msk-authentication.html and am able to connect to the cluster without Kafka proxy successfully.  

In trying to configure Kafka Proxy to allow for passthrough TLS authentication from a client to the MSK cluster.

To generate the cert and key I am running 
```
openssl pkcs12 -in keystore.p12  -nokeys -out cert.pem
openssl pkcs12 -in keystore.p12  -nodes -nocerts -out key.pem
```

I then am trying to run the following command locally on my Mac.

```
./kafka-proxy server --bootstrap-server-mapping "<msk-broker-1>:9094,0.0.0.0:30001" \
--bootstrap-server-mapping "<msk-broker-2>:9094,0.0.0.0:30002" \
--debug-enable \
--log-level debug \
--proxy-listener-tls-enable \
--proxy-listener-cert-file cert.pem \
--proxy-listener-key-file key.pem
```

This generates an error `tls: failed to parse private key`

Any advice or suggestions on what might be the problem on the key not being parsed?

**Comment by bdgeise** [comment]
It seems the issue was related to 

```keytool -genkey -keystore kafka.client.keystore.jks -validity 300 -storepass Your-Store-Pass -keypass Your-Key-Pass -dname "CN=Distinguished-Name" -alias Example-Alias -storetype pkcs12````  

By updating the command to be 
```
keytool -genkey -keyalg RSA -keysize 2048 -keystore kafka.client.keystore.jks -validity 300 -storepass Your-Store-Pass -keypass Your-Key-Pass -dname "CN=Distinguished-Name" -alias Example-Alias -storetype pkcs12
```

I was then able to load the key.

**Comment by srikanthvpai** [comment]
Hello @bdgeise  . Question : Did you have to use any special encodings in openssl to get this working ? I am not able to get the kafka-proxy to read my server.crt

**Comment by bdgeise** [comment]
Hey @srikanthvpai 

No special encodings.  I used the commands above to create the certificates which were then signed by an AWS private root cert.  Are you receiving the `tls: failed to parse private key` error or something different?

**Comment by srikanthvpai** [comment]
Hey @bdgeise 

No. I am receiving tls:unknown certificate. I was not using a cert signed by AWS private root cert. Do we have to use a cert signed by AWS private root cert given by Amazon itself? No other options ? 

Regards

**Comment by bdgeise** [comment]
@srikanthvpai 

The reason we used the AWS private root cert is because of using MSK and that being the way to apply TLS.  We have TLS enabled on the proxy for both sides (Client and MSK).  One thing to check is if your certificate is using the correct starting naming conventions.

**Comment by srikanthvpai** [comment]
Got it . Thank you @bdgeise  . We cannot use Amazon issued cert. So have to add another SSL layer in between.  Companies have their own restrictions to use custom certificates. I am wondering why they made the tls of msk so specific to accept a cert signed by Amazon only.
