### ISSUE TITLE
tls: failed to parse private key

### ISSUE THREAD

**Issue by genebean** [grepplabs/kafka-proxy#168]
It seems no matter what I try, I get `FATA[2024-05-31T13:54:08-04:00] tls: failed to parse private key` in my console when trying to connect to a Kafka cluster that does certificate based auth. 

For testing, I ran this and connected successfully: 

```bash
openssl s_client -CAfile ~/.ssh/ca-certs.pem \
-cert ~/.ssh/user-cert.pem \
-key ~/.ssh/user-key.pem \
-connect example-kafka.example.net:9091
```

The command for connecting that I am trying is: 

```bash
./kafka-proxy server \
--bootstrap-server-mapping "localhost:19092,0.0.0.0:30001" \
--dial-address-mapping "localhost:19092,example-kafka.example.net:9091" \
--tls-enable --tls-ca-chain-cert-file "./.ssh/ca-certs.pem" \
--tls-client-cert-file "./.ssh/user-cert.pem" \
--tls-client-key-file "./.ssh/user-key.pem" \
--tls-client-key-password $CERT_PW \
--debug-enable
```

That prints this out:

```bash
INFO[2024-05-31T14:00:44-04:00] Starting kafka-proxy version 0.3.9
INFO[2024-05-31T14:00:44-04:00] Bootstrap server localhost:19092 advertised as 0.0.0.0:30001
INFO[2024-05-31T14:00:44-04:00] Listening on 0.0.0.0:30001 ([::]:30001) for remote localhost:19092
FATA[2024-05-31T14:00:44-04:00] tls: failed to parse private key
```

The key starts with `-----BEGIN ENCRYPTED PRIVATE KEY-----` and both the cert and ca files start with `-----BEGIN CERTIFICATE-----`. 

Am I missing something, or should this be working?

**Comment by everesio** [comment]
Only PEM block encrypted according to RFC 1423 was supported.
Kafka Proxy `v0.3.10` adds support of PKCS#8 format.
Please check the new version.

**Comment by genebean** [comment]
No output errors with the updated version, thank you very much!
