### ISSUE TITLE
QUESTION: Using this with Confluent Cloud

### ISSUE THREAD

**Issue by joncourt** [grepplabs/kafka-proxy#17]
QUESTION:

Hi,

For SASL_PLAIN - does this pass through the SASL that i put on my clients to the brokers or is it intended to have it's own SASL credentials which are used for all upstream clients?

Background
I'm having a play with this against confluent cloud with little success so far. I'm attempting to use it as a proxy because the CCloud brokers are in an external vpc which i can't connect directly to.

Regards,
Jon

**Comment by joncourt** [comment]
Ahh. The reverse of what I thought auth local was. I’ll take that paradigm shift and have another look. Thanks for the response.

**Comment by everesio** [comment]
You are welcome
