### ISSUE TITLE
Kafka 3.7.0 and producer error "produce version 10 is not supported"

### ISSUE THREAD

**Issue by msillence** [grepplabs/kafka-proxy#171]
Hi,

We're using the latest version of the proxy 3.1.10 and have a client using 3.7.0 libraries

We are getting the error:

level=info msg="Reading data from local connection on xxx.xxx.xxx.xxx.:9102 from xxx.xxx.xxx.xxx:45932 (kafka-broker:9092) had error: produce version 10 is not supported"

**Comment by dklementowski** [comment]
We had the same problem with the official Java library, that is kafka-clients (org.apache.kafka.clients), though only tried the producer part of it.

Looks like it's this check: https://github.com/grepplabs/kafka-proxy/blob/master/proxy/processor_default.go#L172
For some reasone `kafka-clients` in version 3.7.0 or newer (3.7.1 also being affected) makes `requestKeyVersion.ApiVersion` getting value of `10`. Switching one version back to `3.6.2` resolves the problem.

**Comment by everesio** [comment]
@msillence @dklementowski  The problem should be fixed in the 0.3.11 version
