### ISSUE TITLE
Exposing proxy through istio virtual service

### ISSUE THREAD

**Issue by sudheesh-87** [grepplabs/kafka-proxy#176]
Hi,

I'm trying to expose the proxy through istio virtual service instead of a direct loadbalancer , my k8s proxy pod config is like ,

            - 'server'
            - '--log-format=json'
            - '--bootstrap-server-mapping=<broker IP>:9093,0.0.0.0:19093,<proxy external url> :19093'
            - '--external-server-mapping=<broker IP>:9093,<proxy external url> :19093'
        ports:
          - name: proxy
            containerPort: 19093

And I'm creating a headless service to reach the proxy port 

apiVersion: v1
kind: Service
  name: kafka-proxy-headless
spec:
  clusterIP: None
  ports:
    - name: proxy
      port: 19093
      protocol: TCP
      targetPort: 19093
  selector:
    app: kafka-proxy

Then mapping the service to istio virtual service and external url like below,

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kafka-proxy
spec:
  gateways:
    - istio-system/default-gateway
  hosts:
    - <proxy external url>
  tcp:
    - match:
        - port: 19093
      route:
        - destination:
            host: kafka-proxy-headless
            port:
              number: 19093

The istio gateway is  allowed for TCP traffic on port 19093 , however while trying to connect , I'm getting connection disconnected from istio , is exposing proxu through istio supported ? 

{"@level":"info","@message":"New connection for <broker>:9093","@timestamp":"2024-08-08T04:20:15Z"}
{"@level":"info","@message":"Client closed local connection on 10.12.238.211:19093 from 10.12.221.124:42426 (broker:9093)","@timestamp":"2024-08-08T04:20:15Z"}

**Comment by everesio** [comment]
This does not work. You need at least one port per broker.  When using k8s you need  one "--bootstrap-server-mapping" per broker node. Please check the REAMDE, there are examples how to run proxy in the kubernetes.

**Comment by sudheesh-87** [comment]
The above one is a sample config , I tried with configuring one --bootstrap-server-mapping per broker in my setup , but same issue

**Comment by omarfakhreddine** [comment]
Did you end up getting this to work @sudheesh-87 ?
