### ISSUE TITLE
ACL support?

### ISSUE THREAD

**Issue by yrsh** [grepplabs/kafka-proxy#25]
Does it have ACL or another access control mechanism on proxy level? For example, interception and filtering of messages by senders and target topics. Like gateways filters http messages by theirs headers and target path. The main idea is the same - to bring all the issues of access to the proxy/gateway(or other separate system) without using the built-in Kafka ACL.

**Comment by everesio** [comment]
You can globally prevent operations by forbidding api-key usage (https://kafka.apache.org/protocol#protocol_api_keys) 
e.g. --forbidden-api-keys 20 will prevent DeleteTopics operation. 
When operation is detected, client should be disconnected.

I haven't planned other mechanisms so far.

**Comment by everesio** [comment]
If you require ACL support please free to contribute.
