### ISSUE TITLE
Kafka Authorization

### ISSUE THREAD

**Issue by p53** [grepplabs/kafka-proxy#39]
Hi,

i am thinking of authorizing kafka with kafka-proxy, would it be possible to pass kafka message types to plugins?

**Comment by everesio** [comment]
Hi,
currently only authentication with user/password can be externalized with plugins. It is invoked only during initial connection setup not during message processing.
Authorization and ACLs are not implemented in the proxy.
There is only global flag "forbidden-api-keys" which can restrict some operations.
