### ISSUE TITLE
Custom titles for all fields of JSON formatted logs

### ISSUE THREAD

**Issue by Crazy-Hopper** [grepplabs/kafka-proxy#41]
Hello,

Could you please add options to be able to specify all field titles of JSON structured logs?
E.g. Google's Stackdriver expects a field named "message", but not "@message".

**Comment by everesio** [comment]
Please checkout the [v0.2.2](https://github.com/grepplabs/kafka-proxy/releases/tag/v0.2.2) release

**Comment by Crazy-Hopper** [comment]
Great, thank you very much!
