### ISSUE TITLE
Create Custom Plugins?

### ISSUE THREAD

**Issue by georgejdli** [grepplabs/kafka-proxy#46]
Question:

Would it be possible to develop and integrate custom plugins to perform Authentication and Authorization with kafka-proxy server?

Use case:
* Custom plugin will handle authentication and authorization with an external service
* Authorization will be a simple role check and can be done once on start up instead of a per message basis
* Upon success of both checks the plugin would return a successful response and have kafka-proxy server authenticate using SASL with the kafka brokers

Looking at the plugin code I *think* this would be possible by reusing the plugin/local-auth interface to implement a custom plugin. The plugin would return the bool "authenticated" which I think would be sufficient for my use case

**Comment by everesio** [comment]
Currently you can authenticate with SASL which is performed either locally by proxy or by kafka brokers, not both of them - see "Proxy authentication example" in README.md.
Source code for LDAP auth https://github.com/grepplabs/kafka-proxy/blob/master/cmd/plugin-auth-ldap/main.go

There is no special ACL support in the proxy.

**Comment by georgejdli** [comment]
I see
I think i will need to modify the base code to support the kind of plugin I'm looking for

Thank
