### ISSUE TITLE
kafka proxy expects response from broker for Produce Request with RequiredAcks=0  

### ISSUE THREAD

**Issue by everesio** [grepplabs/kafka-proxy#54]
Symptoms: "open requests buffer is full" as described in https://github.com/grepplabs/kafka-proxy/issues/23

RequiredAcks:
This field indicates how many acknowledgements the servers should receive before responding to the request. **If it is 0 the server will not send any response (this is the only case where the server will not reply to a request)**. If it is 1, the server will wait the data is written to the local log before sending a response. If it is -1 the server will block until the message is committed by all in sync replicas before sending a response.

**Comment by radekg** [comment]
Hey @everesio, I already asked on https://github.com/grepplabs/kafka-proxy/issues/23. Would you mind pointing out to the place in the code where this can be fixed? I can prepare a pr.

**Comment by everesio** [comment]
Hi @radekg 
I've already worked on the issue on the https://github.com/grepplabs/kafka-proxy/commits/bugfix/produce-ack-0
The fix is ready, but is need some more tests.

**Comment by everesio** [comment]
Fixed in release 0.2.5.

**Comment by radekg** [comment]
Hey @everesio. Thank you, we are going to run this under test now and I'll give you an update

One thing that came to my mind with regards to the potential perf hit. It is not possible to change the producer acks during an existing connection. That would imply that for each tuple of (connection, producer-id), it should be possible to infer `acks` based on the first produce message for a given producer on a given connection.

I'm going to have a look at that.

**Comment by radekg** [comment]
In our tests, it came up that the impact of this fix is so insignificant that it does not make sense to pursue any further optimizations. Thank you.
