### ISSUE TITLE
TLS Handshake Error with auth-ldap

### ISSUE THREAD

**Issue by ashishgidh** [grepplabs/kafka-proxy#55]
Hi @gustavomcarmo

I tried your suggestion and tests with TLS and auth-ldap. All works fine without TLS but I'am getting a handshake error. Not sure what is missing. 

Here are my details in case you can catch it for us (attaching error.txt)
[error.txt](https://github.com/grepplabs/kafka-proxy/files/4905470/error.txt)

 Any help is highly appreciated. Thanks. 

===================================

**Comment by everesio** [comment]
This look like a problem with certificates. 
How does the openssl.conf  look like ?
What is the output of 
* openssl s_client -connect localhost:9092
* openssl s_client -connect localhost:9092 | openssl x509 -text
assuming proxy is listening on TLS localhost:9092

**Comment by ashishgidh** [comment]
> * openssl s_client -connect localhost:9092 | openssl x509 -text

===============

Thanks @everesio 

Here is the openssl.conf 
[openssl.conf.txt](https://github.com/grepplabs/kafka-proxy/files/4906195/openssl.conf.txt)

also attaching the two commands you suggested. 
[log2.txt](https://github.com/grepplabs/kafka-proxy/files/4906196/log2.txt)
[log1.txt](https://github.com/grepplabs/kafka-proxy/files/4906197/log1.txt)

$ openssl s_client -connect localhost:9092 | openssl x509 -text > log2.txt
Can't use SSL_get_servername
depth=0 C = US, ST = New Jersey, L = NJ, O = chubb, OU = Architecture Shared Service
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, ST = New Jersey, L = NJ, O = chubb, OU = Architecture Shared Service
verify return:1

**Comment by everesio** [comment]
You are connecting with tls to localhost, but you cert does not return Common Name = localhost
Cert returned by the proxy should provide sth like

Subject: **CN = localhost**, C = US, ST = New Jersey, L = NJ, O = chubb, OU = Architecture Shared Service

**Comment by ashishgidh** [comment]
> You are connecting with tls to localhost, but you cert does not return Common Name = localhost
> Cert returned by the proxy should provide sth like
> 
> Subject: **CN = localhost**, C = US, ST = New Jersey, L = NJ, O = chubb, OU = Architecture Shared Service

Oh thanks a lot. Let me try.

**Comment by ashishgidh** [comment]
Certificate issue.
