### ISSUE TITLE
mutual ssl based authentication

### ISSUE THREAD

**Issue by ssahovic** [grepplabs/kafka-proxy#63]
Hi,
is it possible to setup mutual ssl based authentication between client and kafka-proxy. Not between kafka-proxy and kafka broker, but between client and kafka-proxy (client<->kafka-proxy)? 
What I need is, that kafka client users are authenticating themselves against kafka-proxy with their unique client tls certificates before they are routed to the kafka-broker from kafka-proxy.
Thanks.

**Comment by everesio** [comment]
Hi,
please check https://github.com/grepplabs/kafka-proxy/issues/40
