### ISSUE TITLE
Propagate Client Certificate

### ISSUE THREAD

**Issue by itsmjeu** [grepplabs/kafka-proxy#66]
Hi there, 

Is there any way to propagate the client certificate on the proxy? 

We are authenticating our clients using their certificate and we would like that proxy presents the certificate to the server as it is sent by the client. 

Cheers,

Elton

**Comment by everesio** [comment]
Hi @itsmjeu,
client certificate propagation is not supported, but this would be a really nice feature.
Please free to contribute.

**Comment by rounakdatta** [comment]
Hello @everesio, this issue is interesting, and I recently came across an use case. I'm willing to work on a PR for this.

**Comment by everesio** [comment]
Solution would require configuration of the kafka client private key on the proxy - signature in the certificateVerifyMsg
