### ISSUE TITLE
Kerberos authentication to Kafka brokers

### ISSUE THREAD

**Issue by dkhamitov** [grepplabs/kafka-proxy#79]
Looks like it's not possible for a client behind kafka-proxy or kafka-proxy itself to authenticate themselves to Kafka brokers with Kerberos credentials? How difficult could it be to support this use case? I can see the underlying 3rd-party [Sarama](https://github.com/Shopify/sarama) library supports Kerberos authentication.

Also, would you happen to know if there exists a workaround to achieve the subj with the current version?

Thanks for doing a great job.

**Comment by everesio** [comment]
Kerberos has been implemented
