### ISSUE TITLE
List of supported Kafka versions

### ISSUE THREAD

**Issue by pecigonzalo** [grepplabs/kafka-proxy#84]
Hello! Thanks for this great project, Im looking to understand the versions of Kafka that are supported, but the only thing I could find was `Kafka 2.4.0 support` in `v0.2.0`. Is that the latest version that is supported?

I think it would be helpful to add a list of them to the README, I tried parsing it from code but was unable to.

Thanks!

**Comment by everesio** [comment]
I've just added Kafka 2.8.0 support in v0.2.9 version.
