### ISSUE TITLE
Add support for Kafka 2.8

### ISSUE THREAD

**Issue by chromy96** [grepplabs/kafka-proxy#85]
Hi, 

Thanks for the great project. 
I've noticed that using kafka 2.7.1 CLI clients (e.g. `kafka-topics.sh`) works nicely with kafka-proxy, while using version 2.8.0 returns the following error in the kafka-proxy log:

`{"@level":"info","@message":"Reading data from kafka-0.kafka:9092 had error: Unsupported response schema version 11 for key 3 ","@timestamp":"2021-07-08T10:43:21Z"}`

Kafka broker version: 2.8.0
Kafka client: 2.8.0
kafka-proxy: 0.2.8

**Comment by everesio** [comment]
Thank you for reporting 
I will add support for 2.8 soon

**Comment by everesio** [comment]
@chromy96 I've just added support of kafka 2.8.0 to the kafka proxy v0.2.9. Please check it out.
