### ISSUE TITLE
Enable topic mapping by changing requests/replies data

### ISSUE THREAD

**Issue by zaghdous** [grepplabs/kafka-proxy#94]
Hi,
thank you for your valuable work !
I just want to suggest you some evolution that can be useful.
In a multi-tenant kafka deployment, created kafka topics are most of the time prefixed with [${tenantId}-xxx-]topicName. By this way topic is logically created in the namespace ${tenantId}-xxx.

The customer/tenant application using the topic should not be aware of the prefix "${tenantId}-xxx" and a proxy like yours that already handle authentication could easily intercept appropriate messages deserialize them and inject the given prefix.
By this way the mapping topicName <-->  ${tenantId}-xxx-topicName is transparent to customer application.

I did not study the protocol and cannot evaluate the operation complexity but do you think it's easily feasible ?
Another drawback is that you should need to maintain a protocol compatibility, does it change often ?

Thank for your reply.
Sabri

**Comment by everesio** [comment]
Hi,
I am not sure that such a topic name re-mapping is a common use case and it should be a part of the proxy.  
additionally topic is very common field and it is present is multiple requests and responses (and theirs versions).
this feature would be quite a change and cause a performance penalty.
