### ISSUE TITLE
Proxy compatible with Kafka v3.1.0?

### ISSUE THREAD

**Issue by zodiac612** [grepplabs/kafka-proxy#97]
Hello,
i just tried this proxy in combination with Kafka Version 3.1.0 and it doesn't work anymore.
<strike>I got the error:
Connection to node -1 (-------/-----------:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue. (org.apache.kafka.clients.NetworkClient)</strike>

There was a mistake in the proxy configuration, but i got another error:
Unsupported response schema version 12 for key 3 

I plan to use the proxy as SASL "Authenticator", which worked in the past. One of my consumers is not yet able to use SASL_SSL.

Can you give me a hint how to solve the issue or when the kafka proxy will be updated?

Thank you

**Comment by everesio** [comment]
please try out the kafka-proxy v0.3.1 version for the Kafka Version 3.1.0 support

**Comment by zodiac612** [comment]
the new version is working fine again,
Thank you
